//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TP_OH_IIT_2020_API
{
    using System;
    using System.Collections.Generic;
    
    public partial class AnswersTable
    {
        public int answerID { get; set; }
        public string answerString { get; set; }
        public int questionID { get; set; }
        public bool isCorrectAnswer { get; set; }
        public string answerTrivia { get; set; }
    
        public virtual QuestionsTable QuestionsTable { get; set; }
    }
}
