//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TP_OH_IIT_2020_API
{
    using System;
    using System.Collections.Generic;
    
    public partial class EventsTable
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EventsTable()
        {
            this.EarnedCreditsFromEventTables = new HashSet<EarnedCreditsFromEventTable>();
            this.EventTimings = new HashSet<EventTiming>();
        }
    
        public int eventID { get; set; }
        public string eventName { get; set; }
        public string eventDescription { get; set; }
        public int creditsToEarn { get; set; }
        public string qrCodeString { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EarnedCreditsFromEventTable> EarnedCreditsFromEventTables { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EventTiming> EventTimings { get; set; }
    }
}
