//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TP_OH_IIT_2020_API
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuestionsTable
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public QuestionsTable()
        {
            this.AnswersTables = new HashSet<AnswersTable>();
        }
    
        public int questionID { get; set; }
        public int quizIDFK { get; set; }
        public string questionString { get; set; }
        public string questionHint { get; set; }
        public string questionTrivia { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AnswersTable> AnswersTables { get; set; }
        public virtual QuizTable QuizTable { get; set; }
    }
}
