//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TP_OH_AdminControlPanel
{
    using System;
    using System.Collections.Generic;
    
    public partial class AwardsTable
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AwardsTable()
        {
            this.AwardRedemptions = new HashSet<AwardRedemption>();
        }
    
        public int awardID { get; set; }
        public string awardName { get; set; }
        public string awardDescription { get; set; }
        public int awardLimit { get; set; }
        public int creditsRequired { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AwardRedemption> AwardRedemptions { get; set; }
    }
}
